// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo8tVxrVZND0F8TeaTXLSL71Pazd4nHfE',
    appId: '1:626537202001:web:45fc09e36ec55fcc585370',
    messagingSenderId: '626537202001',
    projectId: 'flutter-firebase-ab78d',
    authDomain: 'flutter-firebase-ab78d.firebaseapp.com',
    storageBucket: 'flutter-firebase-ab78d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrqypKZk0WWNXWWsRg9FrqzK42CwkYmUI',
    appId: '1:626537202001:android:2f5783cc59297db8585370',
    messagingSenderId: '626537202001',
    projectId: 'flutter-firebase-ab78d',
    storageBucket: 'flutter-firebase-ab78d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmxExhFvOu-tmel2lW7LVF0sBv73T7nY',
    appId: '1:626537202001:ios:5c65017d45826884585370',
    messagingSenderId: '626537202001',
    projectId: 'flutter-firebase-ab78d',
    storageBucket: 'flutter-firebase-ab78d.appspot.com',
    iosClientId: '626537202001-kb43bkvl2oiln5m748radenbimfm65ja.apps.googleusercontent.com',
    iosBundleId: 'stevegregor1outlook.flutterFirebase',
  );
}
